import type { CalendarEvent, Lead, SearchHistoryItem } from './types'

export const demoLeads: Lead[] = [
  {
    id: 'lead_1',
    placeId: 'place_northside_dental',
    businessName: 'Northside Family Dental',
    phoneNumber: '(312) 555-0198',
    website: null,
    address: '2140 N Damen Ave, Chicago, IL',
    rating: 4.2,
    reviewCount: 18,
    category: 'Dentist',
    googleMapsUrl: 'https://www.google.com/maps',
    city: 'Chicago',
    state: 'IL',
    dateAdded: '2026-06-02',
    leadScore: 91,
    scoreReasons: ['No website', 'Good rating', 'Some review traction', 'Service-based category', 'Phone available'],
    status: 'New',
    notes: 'No website found. Strong fit for web design outreach.',
    tags: ['No website', 'Healthcare'],
    followUpDate: '2026-06-18',
    missingSocialLinks: true,
    missingContactMethods: true,
  },
  {
    id: 'lead_2',
    placeId: 'place_austin_auto_glass',
    businessName: 'Austin Auto Glass',
    phoneNumber: '(512) 555-0144',
    website: 'https://example.com',
    address: '1401 E 7th St, Austin, TX',
    rating: 3.9,
    reviewCount: 42,
    category: 'Auto repair',
    googleMapsUrl: 'https://www.google.com/maps',
    city: 'Austin',
    state: 'TX',
    dateAdded: '2026-06-04',
    leadScore: 74,
    scoreReasons: ['Some review traction', 'Service-based category', 'Phone available'],
    status: 'Contacted',
    notes: 'Website is dated and not mobile optimized.',
    tags: ['SEO', 'Redesign'],
    followUpDate: '2026-06-20',
    missingSocialLinks: false,
    missingContactMethods: false,
  },
  {
    id: 'lead_3',
    placeId: 'place_bright_path_tutoring',
    businessName: 'Bright Path Tutoring',
    phoneNumber: '(602) 555-0172',
    website: null,
    address: '88 E Camelback Rd, Phoenix, AZ',
    rating: 4.8,
    reviewCount: 9,
    category: 'Tutoring service',
    googleMapsUrl: 'https://www.google.com/maps',
    city: 'Phoenix',
    state: 'AZ',
    dateAdded: '2026-06-06',
    leadScore: 88,
    scoreReasons: ['No website', 'Good rating', 'Service-based category', 'Phone available'],
    status: 'Interested',
    notes: 'Owner asked for examples of local-service websites.',
    tags: ['No website', 'Education'],
    followUpDate: '2026-06-17',
    missingSocialLinks: true,
    missingContactMethods: false,
  },
  {
    id: 'lead_4',
    placeId: 'place_harbor_pet_grooming',
    businessName: 'Harbor Pet Grooming',
    phoneNumber: '(206) 555-0155',
    website: null,
    address: '721 Pine St, Seattle, WA',
    rating: 4.1,
    reviewCount: 13,
    category: 'Pet groomer',
    googleMapsUrl: 'https://www.google.com/maps',
    city: 'Seattle',
    state: 'WA',
    dateAdded: '2026-06-08',
    leadScore: 86,
    scoreReasons: ['No website', 'Some review traction', 'Service-based category', 'Phone available'],
    status: 'Follow-up',
    notes: 'Needs booking form and local SEO help.',
    tags: ['No website', 'Booking'],
    followUpDate: '2026-06-15',
    missingSocialLinks: true,
    missingContactMethods: true,
  },
  {
    id: 'lead_5',
    placeId: 'place_summit_roof_repair',
    businessName: 'Summit Roof Repair',
    phoneNumber: '(720) 555-0129',
    website: 'https://example.com',
    address: '1550 Wewatta St, Denver, CO',
    rating: 3.7,
    reviewCount: 66,
    category: 'Roofing contractor',
    googleMapsUrl: 'https://www.google.com/maps',
    city: 'Denver',
    state: 'CO',
    dateAdded: '2026-06-09',
    leadScore: 69,
    scoreReasons: ['High review count', 'Service-based category', 'Phone available'],
    status: 'New',
    notes: 'High-value category. Weak reviews suggest reputation work.',
    tags: ['Reputation', 'SEO'],
    followUpDate: '2026-06-22',
    missingSocialLinks: false,
    missingContactMethods: false,
  },
]

export const searchHistory: SearchHistoryItem[] = [
  { id: 's1', keyword: 'dentists without websites', city: 'Chicago', state: 'IL', radius: 25, leadsReturned: 43, creditsUsed: 39, resultCount: 43, createdAt: '2026-06-10' },
  { id: 's2', keyword: 'roofing contractors', city: 'Denver', state: 'CO', radius: 35, leadsReturned: 88, creditsUsed: 81, resultCount: 88, createdAt: '2026-06-09' },
  { id: 's3', keyword: 'pet groomers', city: 'Seattle', state: 'WA', radius: 20, leadsReturned: 27, creditsUsed: 24, resultCount: 27, createdAt: '2026-06-08' },
]

export const calendarEvents: CalendarEvent[] = [
  { id: 'e1', leadId: 'lead_4', title: 'Call Harbor Pet Grooming', type: 'Call', startsAt: '2026-06-15T15:00:00' },
  { id: 'e2', leadId: 'lead_3', title: 'Send proposal to Bright Path', type: 'Follow-up', startsAt: '2026-06-17T10:30:00' },
  { id: 'e3', leadId: 'lead_1', title: 'Discovery meeting', type: 'Meeting', startsAt: '2026-06-18T13:00:00' },
]
